### ISSUE TITLE
`for _ in <number>` re-instentiates elements when the number gets dirty.

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#9218]
### Bug Description

In the example above, pressing the button makes the number dirty (despite not changing its value) and the element are re-instentiated, so pressing the button will clear all the checkboxes.

Ideally the checkbox wouldn't be re-instentiated also if the number is increased or decreased.

A bit similar to https://github.com/slint-ui/slint/issues/3953 and can probably be solved in a similar way with an IntModel instead of a BoolModel

### Reproducible Code (if applicable)

```slint
import { AboutSlint, Button, VerticalBox, CheckBox } from "std-widgets.slint";

export component Demo {
    property <bool> condition;
    property <int> number: condition ? 2 : 2;
    VerticalBox {
        alignment: start;
        Button {
            text: "Click me";
            clicked => { condition = !condition }
        }
        for x in number : CheckBox {
            init => { debug("init", x) }
            text: "Checkbox";
        }
    }
}
```

### Environment Details

_

**Comment by YohDeadfall** [comment]
I started working on the issue, but it turned out that the following comment isn't accurate:

https://github.com/slint-ui/slint/blob/2642a713fccd10f80c714effeab2f904cd464f25/internal/interpreter/dynamic_item_tree.rs#L121-L122

The repro never hits the first branch designed for `bool` as `is_conditional` is set for conditions only and never for loops. So, my question what should be fixed in that case: the comment or the code producing repeatable elements?

**Comment by ogoffart** [comment]
I understand that this comment is a bit ambiguous.
When `is_conditional` is true, it is a `if` condition. But it is `false` for for loop.
See also https://docs.rs/i-slint-compiler/latest/i_slint_compiler/object_tree/struct.RepeatedElementInfo.html#structfield.is_conditional_element

(I have now clarified the comment)

**Comment by tilladam** [comment]
Still reproduces on current master (`a84bb1dd52`).

Driving the snippet above with synthetic input and reading the checkbox state back:

| step | first checkbox |
| --- | --- |
| check it | `checked == true` |
| click "Click me" | `checked == false` — reset |

The button only flips `condition`, and `number` is `condition ? 2 : 2`, so the count never actually changes value — it only becomes dirty. The checkboxes are re-instantiated anyway, which is exactly what the description reports.

Control, to show the reset is caused by that button and not by any interaction: with the first checkbox checked, clicking the *other* checkbox instead leaves the first one checked (both end up `checked == true`). Only the button click clears it.

**Comment by tilladam** [comment]
Still reproduces on master (`38b07bb99`), and there's a second trigger worth recording: the count binding can be re-dirtied by *layout* rather than by a click, so the pool is rebuilt continuously instead of once per interaction.

```rust
slint::slint! {
    export component Ui inherits Window {
        width: 300px;
        height: 300px;
        in property <length> h: 100px;
        out property <int> init-count: 0;

        VerticalLayout {
            // floor(100/50) == floor(110/50) == 2: the count never changes value,
            // the binding only becomes dirty.
            for i in floor(root.h / 50px): Rectangle {
                height: 10px;
                init => { root.init-count += 1; }
            }
        }
    }
}
```

Setting `h` from `100px` to `110px` and dispatching an event:

| step | `init-count` |
| --- | --- |
| after `Ui::new()` | 2 |
| after `h = 110px` (count still 2) | **4** |
| after `h = 210px` (count now 4) | 8 |

The shape that bites in practice is a count derived from a geometry property, such as `floor(parent.height / row-height) + 5`. That looks static, but it re-evaluates on every layout pass, so every instance is destroyed and recreated continuously — losing per-item state the whole time, not just when the user does something. It's the same root cause as the original report, but the failure is much harder to attribute, since nothing in the UI appears to have changed.
